spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/interviewPrep;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

    master:
      hikari:
        username: root
        password: masterpw
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://mysql-master:3306/interviewprep?useSSL=false&allowPublicKeyRetrieval=true


    slave:
      hikari:
        username: root
        password: slavepw
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://mysql-slave:3306/interviewprep?useSSL=false&allowPublicKeyRetrieval=true

  jpa:
    hibernate:
      ddl-auto: update

  profiles:
    include: oauth

  redis:
    host: localhost
    port: 6379

  flyway:
    enabled: false
    baseline-on-migrate: true

logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace

jwt:
  secret: "12345678901234567890123456789010"

---
spring:
  profiles: mariadb
  datasource:
    url: jdbc:mariadb://mariadb:3306/test
    username: root
    password: root1234
    driver-class-name: org.mariadb.jdbc.Driver

  redis:
    host: redis-server
    port: 6379


